### ISSUE TITLE
Question: Publishing package source

### ISSUE THREAD

**Issue by shivan1b** [aptly-dev/aptly#835]
Hello!

I have been trying to publish a multi component repository which has been made by mirrors with the setting `downloadSourcePackages` set to `true`.
When I publish it however, only the `.deb` files are added in the published repo.

My `aptly.conf`:
```
{ 
  "rootDir": "/opt/aptly",
  "downloadConcurrency": 30,                                                                                         
  "downloadSpeedLimit": 0,                                                                                           
  "architectures": ["amd64", "arm64", "armel", "armhf", "i386"],                                                     
  "dependencyFollowSuggests": false,                                                                                 
  "dependencyFollowRecommends": false,                                                                               
  "dependencyFollowAllVariants": false,                                                                              
  "dependencyFollowSource": false,                                                                                   
  "gpgDisableSign": false,                                                                                            
  "gpgDisableVerify": false,                                                                                          
  "downloadSourcePackages": true,                                                                                     
  "ppaDistributorID": "ubuntu",                                                                                       
  "ppaCodename": "",                                                                                                  
  "S3PublishEndpoints": {},                                                                                           
  "SwiftPublishEndpoints": {}                                                                                         
}
```

Command used for publishing:
```
# aptly publish snapshot -skip-contents -skip-signing -component=,, mypackage-main-w-inhouse-May-22-2019 mypackage-contrib-May-22-2019 mypackage-non-free-May-22-2019
```

Details about the published snapshot:
```
Prefix: .                                                                                                             
Distribution: testing                                                                                                 
Architectures: amd64 arm64 armel armhf i386                                                                           
Sources:                                                                                                              
  main: mypackage-2.1-main-w-inhouse-May-22-2019 [snapshot]                                                              
  contrib: mypackage-2.1-contrib-May-22-2019 [snapshot]                                                                   
  non-free: mypackage-2.1-non-free-May-22-2019 [snapshot]
```

Output of `aptly publish list`
```
 * ./testing [amd64, arm64, armel, armhf, i386] publishes {contrib: [mypackage-contrib-May-22-2019]: Snapshot from mirror [testing-contrib-source]: http://deb.debian.org/debian/ testing [src]}, {main: [mypackage-main-w-inhouse-May-22-2019]: Merged from sources: 'mypackage-inhouse-May-22-2019', 'mypackage-main-May-22-2019'}, {non-free: [mypackage-non-free-May-22-2019]: Snapshot from mirror [testing-non-free-source]: http://deb.debian.org/debian/ testing [src]}
```

Hopefully this provides an idea of the final structure.

Please assist.
